### ISSUE TITLE
Question about ORICA implementation / return values

### ISSUE THREAD

**Issue by sunshineinsandiego** [alejoe91/spyica#36]
Hi - Thanks for porting ORICA from matlab to python. Two quick questions for you:
- Have you verified the output of the matlab implementation vs. your python port?
- Is it possible to pull a list of ICs and unmixing matrix as return values from your ORICA function?
Thanks!

**Comment by alejoe91** [comment]
Hi @sunshineinsandiego 

- The output was verified versus the MATLAb implementation from @goodshawn12 
- You can get all the ICs by multiplying the data by the unmixing matrix ([`self.unmixing`](https://github.com/alejoe91/spyica/blob/master/spyica/orica/orica.py#L163-L166))

Are you running ORICA for spike sorting purposes or are you only interested in the Python implementation?
In the latter case, I think it would be better to make a separate Python package that implements ORICA with a similar API as `scikit-learn` (https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FastICA.html)

**Comment by sunshineinsandiego** [comment]
Just the python implementation, not for spike sorting. Got it, thanks!
